**5月4日の課題**  
1922076 南 昂汰 G4

1. 連立1次方程式をガウス・ジョルダンの消去法で解く関数gauss_jordan_elimination(A,b)をプログラムしてください。
- 次を必ず満たすこと
- Aは行列、bはベクトルを与えることとする。
- 解が一意に定まる場合は解を列ベクトル(numpy array)で返し、不定、不能の場合をその旨をエラーとして返すこと。
- 連立1次方程式を解く関数としてnumpy.linalg.solve(A, b)やscipy.linalg.lu_solve(LU, b), sympy.solve()などがあるが、そのような関数は使わずあくまでもスクラッチからプログラミングすること。
- 必要に応じてコメントを入れること、何もない場合は理解していないものとして、減点対象とする。
- なお、より精度のいいアルゴリズムにするために「ピボット選択」という方法がある。それを調べ、実装している場合は加点評価する。

**<h3>ピボット選択とは</h3>**
対角要素に０が来ると０で割れず、対角要素を１にできない。<br>
そこで、対角要素に０が来ないように行を入れ替える。<br>
さらに、ある値を割る場合、分母の値は絶対値が大きい方が割り算の誤差が小さくなる。<br>
<br>
参考文献・参考資料<br>
イメージングソリューション「ピボット選択を行ったGauss-Jordan法」<br>
https://imagingsolution.net/math/gauss-jordan-with-pivot/

In [0]:
import numpy as np

#連立1次方程式をガウス・ジョルダンの消去法で解く関数(A：行列,b：ベクトル)
def gauss_jordan_elimination(A,b):
    #拡大係数行列を用意
    b=np.reshape( b,(-1,1) )#列ベクトルに変換
    Ab=np.concatenate( (A,b),axis=1 )#横方向に結合
    #行列Aのランクを求める
    A_rank=np.linalg.matrix_rank(A)
    #拡大係数行列のランクを求める
    Ab_rank=np.linalg.matrix_rank(Ab)
    if Ab_rank==A_rank:
      if A_rank == A.shape[1]:
        print("解が一意に定まる")
      else:
        print("不定")
    else:
      print("不能")
    x=Ab.shape[0]#未知数
    #行列の確認
    print("pre matrix=")
    print(Ab)

#ピボット選択-----------------------------------------------------------------------------------------------
    #各行でピボット選択して掃き出す
    for pivot in range(x):
        #ピボット列で成分の絶対値が最大の行を探す
        row_max=pivot
        val_max=Ab[pivot,pivot]
        for row in range(pivot+1,x):
            if ( val_max<abs(Ab[row,pivot]) ):
                row_max=row
                val_max=abs(Ab[row,pivot])
        #ピボットの行と入れ替え
        if (pivot!=row_max):
            Ab[pivot,:],Ab[row_max,:]=Ab[row_max,:],Ab[pivot,:].copy()
        #ピボット行をピボットで割る(Ab[pivot,pivot]=1にする)
        Ab[pivot,:]=Ab[pivot,:]/val_max
        #掃き出し操作で、Ab[pivot,pivot]より下の係数を0にする
        for row in range(0,x):
            #ピボット行をAb[row,pivot]倍してrow行から引く
            if row!=pivot:
                pivot_row=Ab[row,pivot]*Ab[pivot,range(pivot,x+1)]
                Ab[row,range(pivot,x+1)]-=pivot_row
        print(Ab)
#ピボット選択-----------------------------------------------------------------------------------------------

    #行列の確認
    print("Post matrix=")
    print(Ab)
    #解の取り出し
    return Ab[:,x]

2.上記で作った関数を用いて次の3つの連立1次方程式を解いてください。<br>
(1)<br>
4𝑥−7𝑦+4𝑧=1<br>
𝑥+𝑦−𝑧=6<br>
2𝑥+5𝑦−8𝑧=3

In [32]:
A=np.array([
  [ 4., -7., 4.],
  [ 1., 1., -1.],
  [ 2., 5., -8.],
])

b=np.array([1.,6.,3.])

print( "x=",gauss_jordan_elimination(A,b) )

解が一意に定まる
pre matrix=
[[ 4. -7.  4.  1.]
 [ 1.  1. -1.  6.]
 [ 2.  5. -8.  3.]]
[[  1.    -1.75   1.     0.25]
 [  0.     2.75  -2.     5.75]
 [  0.     8.5  -10.     2.5 ]]
[[ 1.          0.         -1.05882353  0.76470588]
 [ 0.          1.         -1.17647059  0.29411765]
 [ 0.          0.          1.23529412  4.94117647]]
[[1. 0. 0. 5.]
 [0. 1. 0. 5.]
 [0. 0. 1. 4.]]
Post matrix=
[[1. 0. 0. 5.]
 [0. 1. 0. 5.]
 [0. 0. 1. 4.]]
x= [5. 5. 4.]


(2)<br>
𝑥+2𝑦−5𝑧=4<br>
2𝑥+3𝑦−7𝑧=7<br>
4𝑥−𝑦+7𝑧=7

In [33]:
A=np.array([
  [ 1., 2., -5.],
  [ 2., 3., -7.],
  [ 4., -1., 7.],
])

b=np.array([4.,7.,7.])

print( "x=",gauss_jordan_elimination(A,b) )

不定
pre matrix=
[[ 1.  2. -5.  4.]
 [ 2.  3. -7.  7.]
 [ 4. -1.  7.  7.]]
[[  1.    -0.25   1.75   1.75]
 [  0.     3.5  -10.5    3.5 ]
 [  0.     2.25  -6.75   2.25]]
[[ 1.  0.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]
[[ 1.  0. nan nan]
 [ 0.  1. nan nan]
 [nan nan nan nan]]
Post matrix=
[[ 1.  0. nan nan]
 [ 0.  1. nan nan]
 [nan nan nan nan]]
x= [nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:38: RuntimeWarning: invalid value encountered in true_divide


(3)<br>
𝑥+2𝑦−5𝑧=4<br>
2𝑥+3𝑦−7𝑧=7<br>
4𝑥−𝑦+7𝑧=8

In [34]:
A=np.array([
  [ 1., 2., -5.],
  [ 2., 3., -7.],
  [ 4., -1., 7.],
])

b=np.array([4.,7.,8.])

print( "x=",gauss_jordan_elimination(A,b) )

不能
pre matrix=
[[ 1.  2. -5.  4.]
 [ 2.  3. -7.  7.]
 [ 4. -1.  7.  8.]]
[[  1.    -0.25   1.75   2.  ]
 [  0.     3.5  -10.5    3.  ]
 [  0.     2.25  -6.75   2.  ]]
[[ 1.          0.          1.          2.21428571]
 [ 0.          1.         -3.          0.85714286]
 [ 0.          0.          0.          0.07142857]]
[[  1.   0.  nan -inf]
 [  0.   1.  nan  inf]
 [ nan  nan  nan  inf]]
Post matrix=
[[  1.   0.  nan -inf]
 [  0.   1.  nan  inf]
 [ nan  nan  nan  inf]]
x= [-inf  inf  inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:38: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:38: RuntimeWarning: invalid value encountered in true_divide
